### ISSUE TITLE
Pyinstaller that targets windows (exe)

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_server#105]
Start on this once #103 + #101 are done to serve as a template for building this.

**Comment by maximlopin** [comment]
Update:

Server used to work after installing it with the windows installer, but after a scipy update it started to throw an error `OSError: [WinError 126] The specified module could not be found`

Here is a similar scipy issue opened yesterday:
https://github.com/scipy/scipy/issues/12400

Downgrading scipy to 1.4.1 solved the problem, but hopefully soon it will be fixed at scipy release
