### ISSUE TITLE
broken server after commit 48615293415bbd1f4d7ad207283090199bc07f9d

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#16]
the server is not connecting on the latest version

last working version was:

48615293415bbd1f4d7ad207283090199bc07f9d

<img width="1129" alt="Screen Shot 2019-05-21 at 12 13 54 PM" src="https://user-images.githubusercontent.com/5898506/58124470-228cc200-7bc3-11e9-83c6-67a9e53b6bcd.png">

**Comment by StpMax** [comment]
fixed by commit 2e77f0e08fadcec5cab920ca403dbc160df9a2ca
