### ISSUE TITLE
save predictor metadata on start and after each phase

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#18]
this is a mindsdb module issue, but refelects on server

* Save metadata as soon as model is created, even if its just the name, 
make sure to add the attributes of datasource name and the fields its being asked to predict as well as initial status: started. And map this to the returned data on the server.

* save after each phase, save the predictor metadata and store the phase at which its at. map the phase name to the status attribute on the server response.

**Comment by George3d6** [comment]
This is mainly done already: https://github.com/mindsdb/mindsdb/blob/master/mindsdb/libs/controllers/transaction.py#L114

that's the first save call, and you'll noticed they are saved after each phase.

The only thing needed doing is the mapping on to status, I'll look into it.

However, the GUI doesn't seem to display the model until it's done training at the moment.

**Comment by torrmal** [comment]
make sure that you start saving metadata hopefully even before phase 1 begins, but if not as soon as first pahse begins.

**Comment by George3d6** [comment]
It is, it is saved as soon as it's created, but querying it from the server seems to cause some errors, I'm fixing those now

**Comment by George3d6** [comment]
This PR allows the server/gui to properly send adapated metadata  through all stages of model training: https://github.com/mindsdb/mindsdb/pull/233

**Comment by George3d6** [comment]
Ok, should be closed by https://github.com/mindsdb/mindsdb/pull/233, please close after reviewing and merging... or, if you forget, I'll just close it tomorrow.
