### ISSUE TITLE
data preparation no being popualted on metadata mapping

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#20]
on the metdata no 'data_preparation' is being mapped,

example of desired output:

 'data_preparation': {
        'accepted_margin_of_error': 0.2,
        'total_row_count': 18000,
        'used_row_count': 10000,
        'test_row_count': 1000,
        'validation_row_count': 1000,
        'train_row_count': 8000
    },

**Comment by George3d6** [comment]
This should be working properly now, feel free to train a model in the GUi and query `http://localhost:5000/predictors/<predictor_name>`, the key `data_preparation` should be among the first to show up on screen at the top level of the object.
