### ISSUE TITLE
used_row_count is not correct

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#21]
Used row count doesnt add up. See response

```
"status": "complete",
    "current_phase": "Trained",
    "name": "nr_rooms",
    "version": "1.2.1",
    "data_preparation": {
        "accepted_margin_of_error": 0.0,
        "total_row_count": 5037,
        "used_row_count": 630,
        "test_row_count": 505,
        "train_row_count": 4029,
        "validation_row_count": 503
    },

```

**Comment by George3d6** [comment]
Isn't `use_row_count` the nr of rows used by the stats generator ? 
In that case, I see no problem with he value.

It's only test + train + validation row count that should add up to total_row_count

**Comment by torrmal** [comment]
as you can see it doesnt add to used_row_count

total is the total in the file 
used_row_count is the total number of rows actually used

please le tme know if this makes sense @George3d6

**Comment by George3d6** [comment]
Yes, changes pushed to mindsdb master, see slack for more details. closing
