### ISSUE TITLE
add predictor accuracy to predictors endpoint

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#22]
GET /predictors does not contain accuracy

```
[
    {
        "name": "nr_rooms",
        "version": "1.2.1",
        "is_active": false,
        "data_source": "home_rentals.csv",
        "predict": [
            "number_of_rooms"
        ],
        "status": "complete",
        "current_phase": "Trained",
        "train_end_at": "2019-05-31T10:56:01",
        "updated_at": "2019-05-31T10:57:02",
        "created_at": "2019-05-31T10:55:00"
    }
]
```

See PredictorStatus entity

**Comment by George3d6** [comment]
Added predictor accuracy on the validation dataset as a whole to both the data for individual predictors and the the array of PredictorStatus data. (Required changes to mindsdb to compute this value, so please use the latest mindsdb master branch to test).
