### ISSUE TITLE
upload large files timeout issue

### ISSUE THREAD

**Issue by torrmal** [mindsdb/mindsdb_server#31]
see this link on how to fix this issue:

https://stackoverflow.com/questions/44727052/handling-large-file-uploads-with-flask

pointer on where this is on the server code:

https://github.com/mindsdb/mindsdb_server/blob/master/mindsdb_server/namespaces/datasource.py#L115

**Comment by surendra1472** [comment]
I think it would be better to upload the file to S3, and from there it will be easy to process.
https://medium.com/@bobhaffner/aws-s3-select-retrieving-subsets-of-tabular-files-7df36cd2d230

**Comment by StpMax** [comment]
done in 7baa7cf817e3c4b95e12c6ae8041d2aa3beea411
Original problem came from 'werkzeug' form-data parser. When processing big bodyes memory usage grows up without stop. So form-data processor changed to [python-multipart](https://github.com/andrew-d/python-multipart)
