### ISSUE TITLE
OS specific distributions

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_server#75]
Create OS specific distributions (e.g. rpm package. snap package, dbm package, whatever are the popular formats on windows/OSX).

This should include a bit of research into (see above) the popular formats we should be supporting for each platform and how easy a distribution for them should be to create.

I *think* that all of the dev should leave their feedback here in terms of:

a) What packages they can easily create because they've done so before
b) What are the common formats in their particular niche of technology

Also this might turn into a community issue once we make progress since we could try and get those packages up onto the official repositories.

Personally I feel comfortable doing the PKGBUILD (arch) and can probably handle the snap, dbm and rpm. Ideally someone else would be in charge of designing the OSx and Windows specific distributions.

For an existing implementation of something like this see the way we build and distribute the docker image.

Once this is done we should also update the docs.

Also, make sure we don't bite more than we can chew, these can be hard to maintain so we should:

a) Only have them for mindsdb_server, which can then be used to install mindsdb, lightwood and dataskilelt
b) Only document the ones that we are sure work and keep the "install manually" instructions in our documentation for those that don't

**Comment by StpMax** [comment]
a-1) I had a little experience with deb packets, think i can take it if necessary.
a-2) and very little experience with nsis installer for windows. Sure there are many better installers exists for windows than nsis, so if someone know it - it will be great.

Overall about task, i think we can get many problems with updating of all it. So first we will need define stable versions of used components, and test it as well as we can.

**Comment by George3d6** [comment]
Well, we can always create a "stable" branch for versions that we ship via installers I guess.

As far as the nsis goes @StpMax , would you have a computer where you can test that kind of installer (i.e. a windows machine) and would it work on the major versions 7 to 10 and more recent windows server versions ?

Also, any idea how annoying it is to work with?

Ideally, we should start with installers that take us only a few hours to get going and if people use them start creating more of them.

But overall I agree we shouldn't get started on this thing right away, again, for now I want to hear people's thoughts and if we do get working on this, it will be towards the end of the week.

**Comment by ZoranPandovski** [comment]
[Fpm](https://github.com/jordansissel/fpm) is quite a good tool for building packages for multiple platforms like packman, deb, rpm and I think it also supports Mac .pkg. The other thing we need to consider is supported versions for e.g in Ubuntu we will have packages for Ubuntu 16.04 64bit (xenial),  Ubuntu 18.04 64bit (bionic), Ubuntu 20 ... etc. To make sure that this will work we will need to have some setup maybe ansible playbooks and Vagrant machines per OS.

**Comment by George3d6** [comment]
@dfernan mentioned that OSX users, even non-technical ones use `.dmg` package formats (and it's what we use for the GUI and it seems to work well on plenty of MacBooks).

I wouldn't bother with compiling stuff... for now, first we need to see if it's doable. Compiling python code is doable in principle but when you add monsters like PyTorch it becomes a bit harder in practice.

@ZoranPandovski can Fpm make python packages that are just installed via pip? Did you use it before? Andy example file we could use as a guideline.

@Ricram2 since you handled the GUI installation, why did you guys choose the installers you did? Are those specifically good for web-like apps or do you think we can generalize anything from there to install mindsdb?

**Comment by StpMax** [comment]
> As far as the nsis goes @StpMax , would you have a computer where you can test that kind of installer (i.e. a windows machine) and would it work on the major versions 7 to 10 and more recent windows server versions ?

I have last version of win10 at home computer and remote access to office computers with winserver 2012 and win10. Nsis is very configurable, i think nsis-installer will work on any windows version. But it not easy to use, and i think we  can find much easier solution for windows. 

About question you addressed to Riche, i think i can answer on it: GUI using electron-builder package to build installers for different platforms. This module only for electron apps. At time when GUI starts development it was only one stable solution for those purpose, and it still most popular. Installers formats was chosen as most popular from list of this module output. 

Electron-builder is one of main source of my small nsis expirience. In old times it was need to write nsis install scripts if you want anything except simple instalation. And that was awfull :)
