### ISSUE TITLE
Create tests for the clickhouse integration

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_server#76]
Create a test-suite for the clickhous integration.

This should include:

* Create a clickhouse data source (and check the data consistency)
* Train a predictor with a clickhouse data source
* Check it's been auto-updated into clickhouse
* Check the table definition for the predictors
* Get a prediction from clickhouse using a clickhouse datasource
* Get a prediction using data inside clickhouse passed via `WHEN`

**Comment by George3d6** [comment]
Some have been created bu we are yet to fully complete these, leaving this open until we have a better idea of the structure we'd want.

**Comment by George3d6** [comment]
@StpMax for now, since we have more time, could you write test cases for the new clickhouse-integration related feature you are implementing ?

**Comment by StpMax** [comment]
yes, will do it
