### ISSUE TITLE
Setup environment for testing databases integration

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_server#81]
Everyone (in the backend team) should setup environment that include:

* Installation of clickhouse
* dev (i.e. with headers) installation of mysql or mariadb
* dev (i.e. with headers) installation of postgres

This is in order to test and work on integration mindsdb (server) with various databases, it's better to have these setup now rather than later since you may run into installation issues (in which case feel free to ask in the backend channel and/or google stuff)

Make sure that all of this is working by running the Unit tests for the Mysql, Potgres and Clickhouse datasource in mindsdb and confirming they pass. (To run those you'll need the extra  datasource dependencies listed here: https://github.com/mindsdb/mindsdb/blob/master/optional_requirements_extra_data_sources.txt)

Please confirm here once you've got everything set up.

**Comment by StpMax** [comment]
all 3 success

**Comment by George3d6** [comment]
Great

Also pinging @ZoranPandovski to try and do this since I guess you'll be pretty heavily involved in the community stuff and still helping with testing, so it's good if you've got everything running.

**Comment by ZoranPandovski** [comment]
I already have this set up too.

**Comment by maximlopin** [comment]
done

**Comment by George3d6** [comment]
@btseytlin  any update on this ? (If all is working for you, feel free to close the issue)

**Comment by George3d6** [comment]
Closed since @btseytlin create the docker tests thus he's obviously also able to test via that in the local environment.
